version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        BUILDTIME_CACHE_BUST: ${BUILDTIME_CACHE_BUST:-$(date +%s)}
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        BUILDTIME_CACHE_BUST: ${BUILDTIME_CACHE_BUST:-$(date +%s)}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume: